{% set name = "python-rex" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python-rex-{{ version }}.tar.gz
  sha256: 7649e2b6d15132971bc46ba67993845712b879ca797459972428b35c5ec79592

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - six

test:
  imports:
    - rex
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cypreess/python-rex
  summary: Python regular expressions for humans
  license: MIT
  # Will PR upstream to package in license file
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
